"""Static, LightRAG-inspired knowledge exploration page.

The page is deliberately data-only: it embeds the published graph payload and
links to the immutable Concept / Article pages.  It does not call an LLM or a
private service from the browser, which keeps a public Bundle reproducible.
"""
from __future__ import annotations

import json
import re
from typing import Any


DATA_RE = re.compile(r"const DATA=(\{.*?\});\n", re.DOTALL)


def extract_graph_data(graph_html: str) -> dict[str, Any]:
    """Extract the JSON payload from a spatial graph page."""
    match = DATA_RE.search(graph_html)
    if not match:
        raise ValueError("graph page does not contain a DATA payload")
    value = json.loads(match.group(1))
    if not isinstance(value, dict):
        raise ValueError("graph DATA payload must be an object")
    return value


def build_explorer_html(
    data: dict[str, Any],
    *,
    title: str = "OKFolio Knowledge Explorer",
    scope_note: str = "Graph-enhanced knowledge exploration with evidence provenance",
) -> str:
    """Render a self-contained explorer for a published graph payload."""
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    safe_title = json.dumps(title, ensure_ascii=False)
    safe_scope = json.dumps(scope_note, ensure_ascii=False)
    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<style>
:root{{color-scheme:light;--bg:#f5f8fc;--panel:#fff;--ink:#142b45;--muted:#71839a;--line:#dce6f0;--blue:#185a9d;--blue-soft:#edf5fc;--teal:#188579;--gold:#b8892e;--red:#bd4545;--shadow:0 14px 38px rgba(25,64,102,.10)}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font:14px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}}button,input{{font:inherit}}a{{color:inherit;text-decoration:none}}
.app{{min-height:100vh;display:grid;grid-template-rows:4px auto 1fr}}.flag{{background:linear-gradient(90deg,var(--red) 0 16%,var(--gold) 16% 20%,var(--blue) 20% 100%)}}
.topbar{{display:flex;align-items:center;justify-content:space-between;gap:22px;padding:16px 28px;background:var(--panel);border-bottom:1px solid var(--line);box-shadow:0 2px 14px rgba(25,64,102,.05)}}.brand{{display:flex;align-items:center;gap:12px}}.seal{{width:40px;height:40px;border-radius:10px;background:var(--blue);display:grid;place-items:center;color:#fff}}.seal svg{{width:23px;height:23px}}.brand h1{{margin:0;font-size:20px;font-weight:600;letter-spacing:.01em}}.brand p{{margin:2px 0 0;color:var(--muted);font-size:12px}}.top-actions{{display:flex;align-items:center;gap:9px}}.top-actions a{{padding:7px 11px;border:1px solid var(--line);border-radius:7px;color:var(--blue);background:#fff;font-size:12px}}.top-actions a.primary{{color:#fff;border-color:var(--blue);background:var(--blue)}}
.workspace{{min-height:calc(100vh - 82px);padding:24px;display:grid;grid-template-columns:265px minmax(480px,1fr) 345px;gap:16px}}.panel{{background:var(--panel);border:1px solid var(--line);border-radius:12px;box-shadow:var(--shadow);min-height:0}}.left,.right{{padding:18px;overflow:auto}}.main{{padding:22px;display:flex;flex-direction:column;min-width:0;overflow:hidden}}
.eyebrow{{font-size:11px;color:var(--red);letter-spacing:.14em;text-transform:uppercase}}h2{{margin:3px 0 5px;font-size:23px;font-weight:600}}.lead{{margin:0;color:var(--muted);font-size:13px}}.query-box{{display:flex;gap:8px;margin:20px 0 13px}}.query{{flex:1;height:42px;padding:0 13px;border:1px solid #c9d9e8;border-radius:8px;outline:0;color:var(--ink);background:#fff}}.query:focus{{border-color:var(--blue);box-shadow:0 0 0 3px rgba(24,90,157,.11)}}.run{{height:42px;padding:0 15px;border:0;border-radius:8px;background:var(--blue);color:#fff;cursor:pointer}}.modes{{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:18px}}.mode{{padding:6px 9px;border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--muted);cursor:pointer;font-size:12px}}.mode.active{{border-color:#a9c9e6;background:var(--blue-soft);color:var(--blue)}}
.section-title{{display:flex;align-items:center;justify-content:space-between;margin:0 0 9px;color:var(--blue);font-size:12px;font-weight:600}}.section-title small{{color:var(--muted);font-weight:400}}.filter{{width:100%;height:35px;padding:0 10px;border:1px solid var(--line);border-radius:6px;outline:0;color:var(--ink);background:#fff}}.filter:focus{{border-color:var(--blue)}}.chips{{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}}.chip{{padding:4px 8px;border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--muted);font-size:11px;cursor:pointer}}.chip.active{{background:var(--blue-soft);border-color:#afd0ec;color:var(--blue)}}.note{{margin-top:18px;padding:11px 12px;border-left:3px solid var(--gold);background:#fffaf0;color:var(--muted);font-size:12px}}.note strong{{display:block;color:var(--gold);font-weight:600;margin-bottom:3px}}.count-grid{{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:18px}}.count{{padding:10px;border:1px solid var(--line);border-radius:8px;background:#fbfdff}}.count strong{{display:block;color:var(--blue);font-size:19px;line-height:1.1}}.count span{{display:block;margin-top:3px;color:var(--muted);font-size:11px}}
.result-head{{display:flex;align-items:baseline;justify-content:space-between;gap:10px;margin:3px 0 10px}}.result-head h3{{margin:0;font-size:14px;font-weight:600}}.result-head span{{color:var(--muted);font-size:11px}}.results{{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px;overflow:auto;padding:2px 2px 12px}}.card{{position:relative;padding:13px 14px 12px;border:1px solid var(--line);border-radius:9px;background:#fff;text-align:left;cursor:pointer;transition:transform .15s,border-color .15s,box-shadow .15s}}.card:hover,.card.active{{transform:translateY(-2px);border-color:#8eb8dd;box-shadow:0 9px 22px rgba(25,64,102,.1)}}.card.active{{border-color:var(--gold);box-shadow:0 0 0 2px rgba(184,137,46,.15)}}.card::before{{content:"";position:absolute;left:0;top:12px;bottom:12px;width:3px;border-radius:0 3px 3px 0;background:var(--blue)}}.card.policy::before{{background:var(--red)}}.card h4{{margin:0 0 6px 8px;font-size:13px;font-weight:600;line-height:1.45}}.card p{{margin:0 0 8px 8px;color:var(--muted);font-size:11px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}}.card-meta{{margin-left:8px;color:var(--muted);font-size:10px}}.empty{{padding:45px 18px;text-align:center;color:var(--muted);border:1px dashed #cbd9e7;border-radius:9px;background:#fbfdff}}
.focus{{margin-top:auto;padding-top:13px;border-top:1px solid var(--line)}}.focus-label{{color:var(--muted);font-size:11px;margin-bottom:7px}}.focus-map{{position:relative;height:205px;border:1px solid var(--line);border-radius:9px;overflow:hidden;background:radial-gradient(circle at 50% 45%,#fff 0,#eef6fc 100%)}}.focus-map svg{{position:absolute;inset:0;width:100%;height:100%}}.focus-map line{{stroke:#9fc1de;stroke-width:1.4;stroke-dasharray:3 4}}.map-node{{position:absolute;max-width:155px;padding:7px 9px;border:1px solid #a9c9e6;border-radius:8px;background:rgba(255,255,255,.94);color:var(--blue);font-size:11px;text-align:center;box-shadow:0 5px 14px rgba(25,64,102,.08);transform:translate(-50%,-50%)}}.map-node.core{{left:50%;top:46%;border-color:var(--gold);color:#8d671d;box-shadow:0 0 0 3px rgba(184,137,46,.12)}}.map-node.neighbor{{font-size:10px;color:var(--ink)}}.map-node.article{{border-color:#abd7cb;color:var(--teal);background:#f5fcfa}}
.right h3{{margin:0 0 7px;font-size:15px;font-weight:600;line-height:1.4}}.detail-type{{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}}.pill{{padding:3px 8px;border-radius:999px;background:var(--blue-soft);color:var(--blue);font-size:10px}}.detail-description{{margin:0 0 16px;color:var(--muted);font-size:12px}}.detail-block{{margin-top:17px}}.detail-block h4{{margin:0 0 7px;padding-bottom:6px;border-bottom:1px solid var(--line);color:var(--blue);font-size:11px;font-weight:600}}.ref-row,.article-row{{padding:9px 0;border-top:1px solid var(--line)}}.ref-row:first-child,.article-row:first-child{{border-top:0}}.ref-row b,.article-row b{{display:block;font-size:12px;font-weight:600}}.ref-row small,.article-row small{{display:block;margin-top:2px;color:var(--muted);font-size:10px}}.evidence{{margin-top:5px;padding-left:8px;border-left:2px solid var(--teal);color:var(--muted);font-size:11px}}.detail-body{{max-height:175px;overflow:auto;padding:10px;border:1px solid var(--line);border-radius:7px;background:#f8fafc;white-space:pre-wrap;color:#465d75;font:11px/1.65 ui-monospace,SFMono-Regular,Menlo,monospace}}.relation-row{{display:block;margin:7px 0;padding:8px 9px;border-left:3px solid var(--blue);border-radius:0 6px 6px 0;background:#f7fbff;cursor:pointer}}.relation-row:hover{{background:var(--blue-soft)}}.relation-row b{{display:block;font-size:11px}}.relation-row small{{color:var(--muted);font-size:10px}}.hint{{min-height:220px;display:grid;place-content:center;text-align:center;color:var(--muted);font-size:12px}}.hint-mark{{width:45px;height:45px;margin:0 auto 10px;display:grid;place-items:center;border:1px solid #c3d8e9;border-radius:50%;background:var(--blue-soft);color:var(--blue)}}
@media(max-width:1180px){{.workspace{{grid-template-columns:235px minmax(420px,1fr)}}.right{{position:fixed;right:18px;top:90px;bottom:18px;width:340px;transform:translateX(calc(100% + 18px));transition:transform .2s;z-index:5}}.right.open{{transform:none}}}}@media(max-width:800px){{.topbar{{padding:13px 16px}}.brand p,.top-actions a:not(.primary){{display:none}}.workspace{{padding:13px;grid-template-columns:1fr;min-height:calc(100vh - 70px)}}.left{{display:none}}.main{{padding:17px;min-height:calc(100vh - 96px)}}.right{{right:13px;top:78px;bottom:13px;width:min(92vw,345px)}}.results{{grid-template-columns:1fr}}}}
</style>
</head>
<body>
<div class="app"><div class="flag"></div>
<header class="topbar"><div class="brand"><div class="seal" aria-hidden="true"><svg viewBox="0 0 32 32" fill="none"><circle cx="8" cy="16" r="3" fill="currentColor"/><circle cx="24" cy="8" r="3" fill="currentColor"/><circle cx="24" cy="24" r="3" fill="currentColor"/><path d="M11 15l10-6M11 17l10 6" stroke="currentColor" stroke-width="2"/></svg></div><div><h1>OKFolio Knowledge Explorer</h1><p>Concept search · graph context · evidence provenance</p></div></div><div class="top-actions"><a href="graph.html">Open 3D graph</a><a class="primary" href="index.html">Wiki index</a></div></header>
<main class="workspace">
<aside class="panel left"><div class="eyebrow">Explore</div><h2>知识探索</h2><p class="lead">从主题、关系和证据开始检索，而不是从一张静态图开始猜。</p><div class="count-grid"><div class="count"><strong id="countConcepts">0</strong><span>Concepts</span></div><div class="count"><strong id="countRefs">0</strong><span>ConceptRefs</span></div><div class="count"><strong id="countArticles">0</strong><span>Articles</span></div><div class="count"><strong id="countRelations">0</strong><span>Relations</span></div></div><div class="section-title" style="margin-top:22px"><span>Filter concepts</span><small id="typeCount"></small></div><input id="filter" class="filter" type="search" placeholder="按标题或摘要筛选…"><div id="chips" class="chips"></div><div class="note"><strong>公开展示范围</strong><span id="scope"></span></div></aside>
<section class="panel main"><div class="eyebrow">Graph-enhanced retrieval</div><h2>Ask the knowledge base</h2><p class="lead">LightRAG 风格的三种入口：局部上下文、全局主题、全部概念。结果均可回到 ConceptRef 和 Article 原文页。</p><div class="query-box"><input id="query" class="query" type="search" placeholder="Search concepts, policy themes, or evidence…"><button id="run" class="run">Explore</button></div><div class="modes"><button class="mode active" data-mode="local">Local context</button><button class="mode" data-mode="global">Global themes</button><button class="mode" data-mode="all">All concepts</button></div><div class="result-head"><h3 id="resultTitle">局部上下文</h3><span id="resultMeta"></span></div><div id="results" class="results"></div><div class="focus"><div class="focus-label">关系焦点 · 选中 Concept 后显示相邻主题与来源 Article</div><div id="focusMap" class="focus-map"></div></div></section>
<aside id="detail" class="panel right"><div class="hint"><div><div class="hint-mark">证据</div><div>选择一个 Concept</div><small>查看关系、ConceptRef 和 Article 来源</small></div></div></aside>
</main></div>
<script>
const DATA={payload};
const TITLE={safe_title};
const SCOPE={safe_scope};
const COLORS={{"分析框架":"#1769aa","政策建议":"#bd4545","数据口径":"#20836f","国际比较":"#bc8b2f","术语解释":"#687c99"}};
const byId=Object.fromEntries(DATA.concepts.map(x=>[x.id,x])),byRef=Object.fromEntries(DATA.refs.map(x=>[x.ref_id,x])),byArticle=Object.fromEntries(DATA.articles.map(x=>[x.article_id,x]));
let mode="local",query="",selected=null;
const queryInput=document.getElementById("query"),filterInput=document.getElementById("filter"),results=document.getElementById("results"),detail=document.getElementById("detail"),focusMap=document.getElementById("focusMap");
document.title=TITLE;document.getElementById("scope").textContent=SCOPE;document.getElementById("countConcepts").textContent=DATA.stats.concepts;document.getElementById("countRefs").textContent=DATA.stats.refs;document.getElementById("countArticles").textContent=DATA.stats.articles;document.getElementById("countRelations").textContent=DATA.stats.relations;
const typeCounts=DATA.stats.types||{{}};const chips=document.getElementById("chips");for(const [type,count] of Object.entries(typeCounts)){{const chip=document.createElement("button");chip.className="chip active";chip.textContent=`${{type}} · ${{count}}`;chip.dataset.type=type;chip.onclick=()=>{{chip.classList.toggle("active");render()}};chips.append(chip)}}
function activeTypes(){{return new Set([...chips.querySelectorAll(".chip.active")].map(x=>x.dataset.type))}}
function related(c){{return DATA.semantic_edges.filter(e=>e.source===c.id||e.target===c.id).map(e=>byId[e.source===c.id?e.target:e.source]).filter(Boolean)}}
function searchable(c){{return `${{c.title}} ${{c.description}} ${{c.body||""}}`.toLowerCase()}}
function matching(){{const text=(query||filterInput.value).trim().toLowerCase(),types=activeTypes();let list=DATA.concepts.filter(c=>types.has(c.type)&&(!text||searchable(c).includes(text)));if(mode==="local"&&selected){{const ids=new Set([selected.id,...related(selected).map(c=>c.id)]);list=list.filter(c=>ids.has(c.id))}}if(mode==="global")list.sort((a,b)=>related(b).length-related(a).length||b.ref_ids.length-a.ref_ids.length);return list}}
function render(){{const list=matching();document.getElementById("typeCount").textContent=`${{list.length}} 个结果`;document.getElementById("resultTitle").textContent=mode==="local"?"局部上下文":mode==="global"?"全局主题":"全部概念";document.getElementById("resultMeta").textContent=`${{list.length}} / ${{DATA.stats.concepts}}`;results.innerHTML="";if(!list.length){{results.innerHTML='<div class="empty">没有匹配的 Concept。尝试换一个关键词或清除筛选。</div>';return}}for(const c of list){{const card=document.createElement("button");card.type="button";card.className="card"+(c.type==="政策建议"?" policy":"")+(selected?.id===c.id?" active":"");card.onclick=()=>select(c);const h=document.createElement("h4");h.textContent=c.title;const p=document.createElement("p");p.textContent=c.description;const m=document.createElement("div");m.className="card-meta";m.textContent=`${{c.type}} · ${{c.ref_ids.length}} Ref · ${{related(c).length}} relations`;card.append(h,p,m);results.append(card)}}}}
function select(c){{selected=c;renderDetail();renderFocus();render()}}
function renderFocus(){{if(!selected){{focusMap.innerHTML='<div class="empty" style="margin:13px">选择一个 Concept，查看局部关系图</div>';return}}const neighbours=related(selected).slice(0,6),articles=[...new Set(selected.articles)].slice(0,3),nodes=[selected,...neighbours,...articles.map(id=>({{id,title:byArticle[id]?.title||id,type:"Article",article:true}}))];focusMap.innerHTML='<svg viewBox="0 0 100 100" preserveAspectRatio="none"><g>'+nodes.slice(1).map((_,i)=>`<line x1="50" y1="46" x2="${{20+i*16}}" y2="${{16+(i%3)*34}}"></line>`).join("")+'</g></svg>';const core=document.createElement("div");core.className="map-node core";core.textContent=selected.title;focusMap.append(core);neighbours.forEach((n,i)=>{{const node=document.createElement("div");node.className="map-node neighbor";node.style.left=`${{20+i*16}}%`;node.style.top=`${{16+(i%3)*34}}%`;node.textContent=n.title;node.onclick=()=>select(n);focusMap.append(node)}});articles.forEach((id,i)=>{{const node=document.createElement("a");node.className="map-node article";node.href=`articles/${{id}}.html`;node.style.left=`${{25+i*24}}%`;node.style.top="84%";node.textContent="Article";focusMap.append(node)}});}}
function renderDetail(){{if(!selected){{detail.innerHTML='<div class="hint"><div><div class="hint-mark">证据</div><div>选择一个 Concept</div><small>查看关系、ConceptRef 和 Article 来源</small></div></div>';detail.classList.remove("open");return}}detail.classList.add("open");const refs=selected.ref_ids.map(id=>byRef[id]).filter(Boolean),rels=DATA.semantic_edges.filter(e=>e.source===selected.id||e.target===selected.id);detail.innerHTML="";const h=document.createElement("h3");h.textContent=selected.title;detail.append(h);const meta=document.createElement("div");meta.className="detail-type";[selected.type,`${{refs.length}} ConceptRef`,`${{selected.articles.length}} Article`,`${{rels.length}} relations`].forEach(t=>{{const p=document.createElement("span");p.className="pill";p.textContent=t;meta.append(p)}});detail.append(meta);const d=document.createElement("p");d.className="detail-description";d.textContent=selected.description;detail.append(d);block("Concept");const body=document.createElement("div");body.className="detail-body";body.textContent=selected.body||"";detail.append(body);if(rels.length){{block("Related concepts");rels.forEach(e=>{{const other=byId[e.source===selected.id?e.target:e.source],row=document.createElement("a");row.href="#";row.className="relation-row";row.innerHTML=`<b>${{other.title}}</b><small>${{e.source_refs.length}} evidence pair(s) · ${{(e.reasons||[]).join("；")}}</small>`;row.onclick=event=>{{event.preventDefault();select(other)}};detail.append(row)}})}}block("ConceptRef evidence");refs.forEach(r=>{{const row=document.createElement("div");row.className="ref-row";const path=(r.section_path||[]).join(" › ");row.innerHTML=`<b>${{r.title}}</b><small>${{r.ref_id}} · ${{path}} · ${{r.page_start?`p. ${{r.page_start}}`:""}}</small>${{r.evidence?.[0]?`<div class="evidence">${{r.evidence[0]}}</div>`:""}}`;detail.append(row)}});block("Source Articles");selected.articles.forEach(id=>{{const a=byArticle[id],row=document.createElement("a");row.className="article-row";row.href=`articles/${{id}}.html`;row.innerHTML=`<b>${{a?.title||id}}</b><small>${{id}} · open source article</small>`;detail.append(row)}});function block(text){{const x=document.createElement("div");x.className="detail-block";x.innerHTML=`<h4>${{text}}</h4>`;detail.append(x)}}}}
document.querySelectorAll(".mode").forEach(button=>button.onclick=()=>{{document.querySelectorAll(".mode").forEach(x=>x.classList.remove("active"));button.classList.add("active");mode=button.dataset.mode;render()}});document.getElementById("run").onclick=()=>{{query=queryInput.value.trim();if(query){{const hit=matching()[0];if(hit)select(hit)}}render()}};queryInput.addEventListener("keydown",e=>{{if(e.key==="Enter")document.getElementById("run").click()}});filterInput.oninput=()=>{{query="";render()}};renderFocus();render();
</script></body></html>'''
